# 配置
server:
  port: 8080
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.23.180:1521:helowin
    username: ming
    password: 123456
  redis:
    host: 192.168.23.180
    port: 6379
    password: hxzy
    database: 10
  jackson:
    time-zone: GMT+8
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.hxzy.entity
  mapper-locations: classpath:/mapper/*.xml
# 自定义验证码
captcha:
  width: 160
  len: 3
  type: png